---
title: "text-wrangling"
output: html_document
date: "2023-10-20"
---

```{r setup, include=FALSE}

# Load libraries
library(tidyverse)
library(countrycode)
library(dplyr)
library(sf)
library(wordcloud)
library(tidytext)
library(gganimate)
library(gapminder)
library(gifski)
library(animation)

gap <- gapminder

#CHARACTER MENTIONS

books <- read_csv("data/harry_potter_books.csv")

# the 70 most appearing characters in the series
characters <- c("regulus", "sirius", "lavender", "cho", "crabbe", "crouch", 
                "fleur", "cedric", "aberforth", "dumbledore", "dudley", "petunia",
                "vernon", "filch", "seamus", "pomfrey", "fudge", "goyle", "hermione", 
                "hagrid", "karkaroff", "krum", "bellatrix", "alice", "frank", 
                "neville", "luna", "xenophilius", "lupin", "draco", "lucius", 
                "narcissa", "maxime", "mcgonagall", "moody", "peter", "harry", 
                "james", "lily", "quirrell", "tom", "voldemort", "rita", "snape", 
                "tonks", "umbridge", "arthur", "bill", "charlie", "fred", "george", 
                "ginny", "molly", "percy", "ron", "dobby", "hedwig", "grawp",
                "myrtle", "aragog", "ollivander", "lockhart", "kreacher", "stan",
                "bathilda", "dean", "parvarti", "flitwick", "kingsley", "sprout")

books_all_words <- books |>
  unnest_tokens(output = word, input = text)

# split apart by word, and filter only words that are desired characters
character_name_locations <- books_all_words |>
  mutate(proportion = row_number() / nrow(books_all_words)) |>
  filter(word %in% characters)

names_by_chapter <- character_name_locations |>
  select(-proportion) |>
  group_by(chapter, book) |>
  count(word) |>
  pivot_wider(names_from = word, values_from = n) |>
  mutate(book_num = as.numeric(gsub(".*?([0-9]+).*", "\\1", book)), 
         chapter_num = as.numeric(gsub(".*?([0-9]+).*", "\\1", chapter))) |>
  arrange(book, chapter)

#split apart the characters by book to add the order variable
for (i in 1:7){
  name <- paste0("book", i)
  assign(name, transpose(names_by_chapter |> filter(book_num == i)))
}

book1 <- do.call(rbind, book1)
book1 <- as.data.frame(book1) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book2 <- do.call(rbind, book2)
book2 <- as.data.frame(book2) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book3 <- do.call(rbind, book3)
book3 <- as.data.frame(book3) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book4 <- do.call(rbind, book4)
book4 <- as.data.frame(book4) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book5 <- do.call(rbind, book5)
book5 <- as.data.frame(book5) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book6 <- do.call(rbind, book6)
book6 <- as.data.frame(book6) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

book7 <- do.call(rbind, book7)
book7 <- as.data.frame(book7) |>
  mutate(chapter_num = as.numeric(chapter_num)) |>
  arrange(chapter_num)

# put them back together, in order so that order is maintained
names_by_chapter <- bind_rows(book1, book2, book3, book4, book5, book6, book7) |>
  mutate(order = row_number())

# make the NAs compatible with the other values
names_by_chapter[is.na(names_by_chapter)] <- 0

# create table that is compatible with bar charts, with order being what the 
# animation will iterate through
names_for_plotting <- names_by_chapter |>
  select(-chapter, -book, -chapter_num, -book_num) |>
  pivot_longer(!order, names_to = "character", values_to = "count") |>
  mutate(count = as.numeric(count))

# create other data table relating the order in the `names_for_plotting` table to 
# the chapter and book numbers
order_numbers <- names_by_chapter |>
  select(order, book_num, chapter_num) |>
  mutate(text = paste0("Book ", book_num, " Chapter ", chapter_num))

write_rds(order_numbers, file = "data/order_numbers.rds")

write_rds(names_for_plotting, file = "data/names_for_plotting.rds")

# create table for visualizing the eight most common names
name_counts <- names_for_plotting |>
  select(-order) |>
  group_by(character) |>
  summarise(
    count = sum(count)
  ) |>
  arrange(desc(count)) |>
  mutate(character = str_to_title(character)) |>
  head(8)

write_rds(name_counts, file = "data/name_counts.rds")

```


```{r setup, include=FALSE}
#SENTIMENT LEXICON
sentiment_data <- get_sentiments("afinn")

write_rds(sentiment_data, file = "sentiment_data.rds")

#MOVIES
movie1 <- read_csv("data/hp1.csv")
movie2 <- read_csv("data/hp2.csv")
movie3 <- read_csv("data/hp3.csv")
movie4 <- read_csv("data/hp4.csv")|>
  mutate(movie = "Harry Potter and the Goblet of Fire") #fixed messed up name
movie5 <- read_csv("data/hp5.csv")
movie6 <- read_csv("data/hp6.csv")
movie7 <- read_csv("data/hp7.csv")
movie8 <- read_csv("data/hp8.csv")

movies_list <- list(movie1, movie2, movie3, movie4, movie5, movie6, movie7, movie8)

movies <- movies_list |>
  reduce(full_join)

#dataset in which each row is a different word for all movies 
movies_all_words <- movies |>
  unnest_tokens(output = word, input = dialog) |>
  mutate(word = tolower(word)) |>
  select(-character)

#movie dataset merged with lexicon to only contain overlapping words
rated_words <- movies_all_words |> 
  inner_join(sentiment_data) |>
  group_by(movie, chapter) |>
  mutate(average_sentiment = mean(value)) |>
  select(-word, -value) |>
  distinct() |> #gets rid of repeated rows
  group_by(movie) |>
  mutate(chapt_num = row_number())

#creates outputted data file needed for shiny app
write_rds(rated_words, file = "shiny_rated_data.rds")

#sentiment average by movie
total_movie_average <- movies_all_words |> 
  inner_join(sentiment_data) |>
  group_by(movie) |>
  mutate(average_sentiment = mean(value)) |>
  select(-chapter, -word, -value) |>
  distinct() |>
  ungroup() |>
  mutate(movie_num = row_number())

#creates outputted data file needed for bar graph
write_rds(total_movie_average, file = "bar_rated_data.rds")
```

